schedules:
- cron: "0 12 * * 1"
  displayName: Weekly build
  branches:
    include:
      - main

jobs:
  - template: job-template.yml
    parameters:
      script: pytest
  - template: job-template.yml
    parameters:
      script: wheel
  # this currently fails on azure, but works locally
  # - template: job-template.yml
  #   parameters:
  #     script: install