
parameters:
  name: script

jobs:
- job: ${{ parameters.script }}
  pool:
    vmImage: 'ubuntu-20.04'

  strategy:
    matrix:
      9.3_3.8:
        containerImage: pymor/dealii_py3.8:47f2bf40dd49a64292e482b59fe6631101fdcc2b
      9.3_3.9:
        containerImage: pymor/dealii_py3.9:47f2bf40dd49a64292e482b59fe6631101fdcc2b

  container: $[ variables['containerImage'] ]

  steps:
  - script: ./.ci/${{ parameters.script }}.bash
